import Landing from '@/components/Landing/Landing'
import Head from 'next/head'
import { useEffect, useState } from 'react'






export default function Home({ projectData }) {
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    setLoading(false)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Landing projectData={projectData} />

      </main>
    </>
  )
}
export async function getServerSideProps() {
  const response = await fetch(`${process.env.BASE_URL}/api/projects`)
  const repo = await response.json()
  //console.log(repo);
  return {
    props: {
      admin: false,
      projectData: repo.projects
    }
  }
}